import { InstanceCode, ModuleCode, ActivityCode, EventCode, HourLiteral, MinuteLiteral, SecondLiteral, ActivityTypeTitle, ActivityTypeCode, DatetimeLiteral, UserStatus, TimeLiteral } from "../../common";
import { RawMember, RawRoom } from "./common";

export interface RawPlanningElement {
    scolaryear: `${number}`,
    codemodule: ModuleCode,
    codeinstance: InstanceCode,
    codeacti: ActivityCode,
    codeevent: EventCode,
    semester: number,
    instance_location: `${string}/${string}`,
    titlemodule: string,
    prof_inst: RawMember[] | null,
    acti_title: string,
    num_event: `${number}`,
    start: `${DatetimeLiteral}`,
    end: `${DatetimeLiteral}`,
    total_students_registered: number,
    title: string | null,
    type_title: ActivityTypeTitle,
    type_code: ActivityTypeCode,
    is_rdv: "0" | "1",
    nb_hours: TimeLiteral | null,
    allowed_planning_start: `${DatetimeLiteral}`,
    allowed_planning_end: `${DatetimeLiteral}`,
    nb_group: number,
    nb_max_students_projet: number | null,
    room: RawRoom | null,
    dates: null,
    module_available: boolean,
    module_registered: boolean,
    past: boolean,
    allow_register: boolean,
    event_registered: UserStatus,
    display: "0" | "1",
    project: boolean,
    rdv_group_registered: `${DatetimeLiteral}|${DatetimeLiteral}` | null,
    rdv_indiv_registered: `${DatetimeLiteral}|${DatetimeLiteral}` | null,
    allow_token: boolean,
    register_student: boolean,
    register_prof: boolean,
    register_month: boolean,
    in_more_than_one_month: boolean
}